// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA320fPY8AT14-7n1IOFI32vH86uPd1EAQ',
    appId: '1:491633325823:web:585e8a3dff6a4a6ea87eca',
    messagingSenderId: '491633325823',
    projectId: 'artex-8fe7b',
    authDomain: 'artex-8fe7b.firebaseapp.com',
    storageBucket: 'artex-8fe7b.firebasestorage.app',
    measurementId: 'G-Z7P8JWWKDD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeCA9g-OYih3l7ScJhXx5vrb_wRUnAqkM',
    appId: '1:491633325823:android:6a8fe298166c89eaa87eca',
    messagingSenderId: '491633325823',
    projectId: 'artex-8fe7b',
    storageBucket: 'artex-8fe7b.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6ZMKNW-Xy7NUH7yKn9uXgTJzju71_sdQ',
    appId: '1:491633325823:ios:bd14d503369be65ca87eca',
    messagingSenderId: '491633325823',
    projectId: 'artex-8fe7b',
    storageBucket: 'artex-8fe7b.firebasestorage.app',
    iosBundleId: 'com.example.artex',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6ZMKNW-Xy7NUH7yKn9uXgTJzju71_sdQ',
    appId: '1:491633325823:ios:bd14d503369be65ca87eca',
    messagingSenderId: '491633325823',
    projectId: 'artex-8fe7b',
    storageBucket: 'artex-8fe7b.firebasestorage.app',
    iosBundleId: 'com.example.artex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA320fPY8AT14-7n1IOFI32vH86uPd1EAQ',
    appId: '1:491633325823:web:696d2368fab20847a87eca',
    messagingSenderId: '491633325823',
    projectId: 'artex-8fe7b',
    authDomain: 'artex-8fe7b.firebaseapp.com',
    storageBucket: 'artex-8fe7b.firebasestorage.app',
    measurementId: 'G-5PZL70ECD2',
  );
}
